name: wifi_hunter
description: A flutter package to hunt down info from all WiFi APs around you.
version: 1.1.1+2
homepage: https://github.com/RyuChk/wifi_scanner
repository: https://github.com/RyuChk/wifi_scanner.git

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1

flutter:
  plugin:
    platforms:
      android:
        package: klydra.wifi_hunter
        pluginClass: WiFiHunterPlugin